### ISSUE TITLE
Не обнуляется значение content для следующего элемента (tag), если тот не задан

### ISSUE THREAD

**Issue by fedorovanton** [bupy7/xml-constructor#2]
**Пример кода:**

```
['tag' => 'phone1', 'content' => '89991234567'],
['tag' => 'phone2'],
```

**Результат:**

```
<phone1>89991234567</phone1>
<phone2>89991234567</phone2>
```

**Решение проблемы:**

В файле: **vendor/bupy7/xml-constructor/src/XmlConstructor.php**
В строчке: **94**
Добавить код:  `else { $content = null; }`

**Примечание:**

 Если приводить к значению **$content = '';** - то контент обнуляется, но присутствует закрывающий тег, что неправильно.

**Comment by bupy7** [comment]
Fixed in [1.2.5](https://github.com/bupy7/xml-constructor/releases/tag/v1.2.5)
